version: '3.7'

services:
  web:
    image: kirosc/cu-sport-apache:latest
    container_name: apache
    restart: 'always'
    volumes:
      - ./cu_sport_booking_system:/var/www/html/cu_sport_booking_system
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks: 
      - cu-sport-network
    environment:
      SERVER_NAME: kirosc.duckdns.org

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: 'always'
    volumes:
      - container-volume:/var/lib/mysql
      - ./database/project_11Apr_4.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    networks: 
      - cu-sport-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cu_sport_booking

volumes:
  container-volume:

networks: 
  cu-sport-network: