version: '3.7'

services:
  web:
    image: kirosc/cu-sport-apache:latest
    container_name: apache
    restart: 'always'
    volumes:
      - ./cu_sport_booking_system:/var/www/app/cu_sport_booking_system
    ports:
      # - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      # - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - 80:80
      - 443:443
    networks: 
      - cu-sport-network
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: 'always'
    # ports:
      # - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - container-volume:/var/lib/mysql
      - ./database/project_11Apr_4.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cu_sport_booking
    ports:
      - "3306:3306"
    networks: 
      - cu-sport-network

volumes:
  container-volume:

networks: 
  cu-sport-network: